name: Determine Changed Files

on:
  workflow_call:
    outputs:
      all_changed_files:
        value: ${{ jobs.determine_changed_files.outputs.all_changed_files }}

jobs:
  determine_changed_files:
    name: Determine Changed Files
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            CHANGED_FILES="$(git diff --name-only "${{ github.event.pull_request.base.sha }}")"
          elif [ ${{ github.event_name }} == 'push' ]; then
            CHANGED_FILES="$(git diff --name-only "${{ github.event.before }}")"
          else
            CHANGED_FILES=""
          fi

          echo "all_changed_files="$CHANGED_FILES"" >> $GITHUB_OUTPUT
